@baseUrl = http://localhost:5080
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "garry",
  "password": "qwertyui",
  "email": "garry@gmail.com",
  "avatarColor": "red",
  "avatarImage": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABQAAAAKACAYAAADD89WhAAAgAElEQVR4Aezdzc8kV5kn7HSLLWWzphBGmsVLeXrAm6YYIRmkxkaokQ0uW4he"
}

###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "Devgbolade",
  "password": "qwertyui"
}

###
GET {{baseUrl}}/{{urlPath}}/signOUT
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/currentuser
Content-Type: application/json
Accept: application/json
withCredentials: true


###
POST {{baseUrl}}/{{urlPath}}/forgot-password
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "email": "devgbolade@io.com"
}

###
POST {{baseUrl}}/{{urlPath}}/reset-password/d2fc5cb6953b271ba40cfb6c3e58a9ce6cc0ca2d
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "password": "qwertyui",
  "confirmPassword": "qwertyui"
}
