@baseUrl = http://localhost:5080

###
GET {{baseUrl}}/health
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/env
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/fibo/8
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/instance
Content-Type: application/json
Accept: application/json
withCredentials: true
